import type { OwnershipMode, OwnershipRule, Plan, Role, Step } from "../core/schema.js";

export interface RenderedFile {
  path: string;
  content: string;
}

export const HEADER_MARK = "<!-- generated by vibeRACI -->";

export function roleById(plan: Plan, id: string): Role {
  const role = plan.roles.find((r) => r.id === id);
  if (!role) throw new Error(`no such role: ${id}`); // unreachable: schema validates this
  return role;
}

export function rulesFor(plan: Plan, roleId: string, mode: OwnershipMode): OwnershipRule[] {
  return plan.ownership.filter((r) => r.roleId === roleId && r.mode === mode);
}

/**
 * Paths another role owns. An agent is told to leave these alone even when no
 * explicit `denied` rule was written, because "not mine" is the safer default
 * than "unlisted, therefore fair game".
 */
export function pathsOwnedByOthers(plan: Plan, roleId: string): OwnershipRule[] {
  return plan.ownership.filter((r) => r.mode === "owns" && r.roleId !== roleId);
}

/**
 * The "do not touch" list, with anything already listed as read-only removed.
 *
 * A path can be both "read this for context" and "owned by someone else", and
 * printing it under both headings makes a reader hunt for the difference
 * between two rules that say the same thing. The read-only heading is the more
 * useful of the two, so it wins.
 */
export function mustNotModify(plan: Plan, roleId: string): OwnershipRule[] {
  const alreadyListed = new Set(rulesFor(plan, roleId, "reads").map((r) => r.glob));
  return [
    ...rulesFor(plan, roleId, "denied"),
    ...pathsOwnedByOthers(plan, roleId),
  ].filter((rule) => !alreadyListed.has(rule.glob));
}

export function stepsForRole(plan: Plan, roleId: string): Step[] {
  return plan.steps.filter((s) => s.roleId === roleId);
}

/** Steps grouped by phase, phases in ascending order. */
export function stepsByPhase(plan: Plan): { phase: number; steps: Step[] }[] {
  const phases = [...new Set(plan.steps.map((s) => s.phase))].sort((a, b) => a - b);
  return phases.map((phase) => ({
    phase,
    steps: plan.steps.filter((s) => s.phase === phase),
  }));
}

/** Ordered as the user will actually work through them. */
export function orderedSteps(plan: Plan): Step[] {
  return stepsByPhase(plan).flatMap((p) => p.steps);
}

export function promptPath(step: Step): string {
  return `.agents/prompts/${step.id}.md`;
}

export function charterPath(role: Role): string {
  return `.agents/${role.id}.md`;
}

export function settingsPath(role: Role): string {
  return `.agents/settings/${role.id}.settings.json`;
}

export function bullets(items: string[]): string {
  return items.map((i) => `- ${i}`).join("\n");
}

export function numbered(items: string[]): string {
  return items.map((item, i) => `${i + 1}. ${item}`).join("\n");
}

export function checkboxes(items: string[]): string {
  return items.map((i) => `- [ ] ${i}`).join("\n");
}

/** Join sections, collapsing the blank-line noise that creeps into templates. */
export function section(...parts: (string | null | undefined | false)[]): string {
  return parts
    .filter((p): p is string => typeof p === "string" && p.trim().length > 0)
    .join("\n\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()
    .concat("\n");
}
