/**
 * Fixed framework wording, translated at render time.
 *
 * Only boilerplate lives here. Project-specific sentences ("Build the chat
 * screen") come from the Plan, written in `plan.meta.locale`. That split is
 * what lets one Plan render into either language without the planner having
 * to write everything twice.
 */
import type { Locale } from "./schema.js";

export interface Strings {
  // shared
  ownedPaths: string;
  readOnlyPaths: string;
  sharedPaths: string;
  deniedPaths: string;
  yourJob: string;
  doneWhen: string;
  // agent charter / prompt
  youAre: string;
  primaryResponsibility: string;
  mustNotModify: string;
  needSomethingElse: string;
  handoffHeading: string;
  handoffRule: (roles: string) => string;
  outOfScopeRule: string;
  humanIsOwner: string;
  // runbook
  runbookTitle: (project: string) => string;
  runbookIntro: string;
  teamHeading: string;
  planHeading: string;
  phaseLabel: (n: number) => string;
  independentNote: string;
  sequentialNote: string;
  stepHeading: (n: number, title: string) => string;
  howToRun: (tool: string) => string;
  copyPromptFrom: (path: string) => string;
  whenFinished: string;
  allDone: string;
  // project docs
  claudeMdIntro: string;
  agentsMdIntro: string;
  generatedBy: string;
  doNotEditByHand: string;
}

const en: Strings = {
  ownedPaths: "Files you own",
  readOnlyPaths: "Read these, do not change them",
  sharedPaths: "Shared files — edit with care",
  deniedPaths: "Do not touch",
  yourJob: "Your job",
  doneWhen: "You are done when",
  youAre: "You are",
  primaryResponsibility: "What you take care of",
  mustNotModify: "What you must not modify",
  needSomethingElse: "If you need to change something else",
  handoffHeading: "Handing off",
  handoffRule: (roles) =>
    `When you finish, write a short summary of what changed for: ${roles}. ` +
    `Keep it to the facts another developer would need: new files, new endpoints, changed data shapes.`,
  outOfScopeRule:
    "If the work requires changing a file outside the list above:\n" +
    "1. Do not change it yourself.\n" +
    "2. Write down exactly what needs to change and why.\n" +
    "3. Tell the user which teammate should handle it.\n" +
    "4. Continue with the parts you can do.",
  humanIsOwner:
    "The human is the owner of this project. Ask them before anything destructive, " +
    "anything involving credentials or deployment, or any decision that would be hard to undo.",
  runbookTitle: (project) => `Building ${project}`,
  runbookIntro:
    "This is your build order. Work through it top to bottom. " +
    "Each step has a prompt to copy into a coding agent — you do not need to write it yourself.",
  teamHeading: "Your AI team",
  planHeading: "The plan",
  phaseLabel: (n) => `Phase ${n}`,
  independentNote:
    "These steps do not depend on each other. Still do them one at a time — two agents working in the same folder will overwrite each other.",
  sequentialNote: "Finish this before starting the next step.",
  stepHeading: (n, title) => `Step ${n} — ${title}`,
  howToRun: (tool) => `Open ${tool} in this project folder.`,
  copyPromptFrom: (path) => `Copy everything in ${path} and paste it in.`,
  whenFinished: "When the agent says it is finished, check the list above, then move to the next step.",
  allDone: "That is the whole plan. Your project should now run.",
  claudeMdIntro:
    "Project guidance for Claude Code. Every agent working in this repository reads this file.",
  agentsMdIntro: "Project guidance for Codex. Every agent working in this repository reads this file.",
  generatedBy: "Generated by vibeRACI",
  doNotEditByHand:
    "Edit your plan and re-generate rather than editing this file by hand — it will be overwritten.",
};

const ko: Strings = {
  ownedPaths: "내가 담당하는 파일",
  readOnlyPaths: "읽기만 하고 고치지 말 것",
  sharedPaths: "같이 쓰는 파일 — 조심해서 수정",
  deniedPaths: "건드리지 말 것",
  yourJob: "할 일",
  doneWhen: "이것들이 되면 완료",
  youAre: "당신의 역할",
  primaryResponsibility: "맡은 일",
  mustNotModify: "고치면 안 되는 것",
  needSomethingElse: "다른 걸 고쳐야 한다면",
  handoffHeading: "다음 사람에게 넘기기",
  handoffRule: (roles) =>
    `작업이 끝나면 무엇이 바뀌었는지 짧게 정리해 주세요. 받는 쪽: ${roles}. ` +
    `다른 개발자가 알아야 할 사실만 적으세요 — 새로 만든 파일, 새 주소(API), 바뀐 데이터 모양.`,
  outOfScopeRule:
    "위 목록 밖의 파일을 고쳐야 하는 상황이라면:\n" +
    "1. 직접 고치지 마세요.\n" +
    "2. 무엇을 왜 바꿔야 하는지 적어두세요.\n" +
    "3. 어느 팀원이 처리해야 하는지 사용자에게 알려주세요.\n" +
    "4. 할 수 있는 나머지 작업은 계속 진행하세요.",
  humanIsOwner:
    "이 프로젝트의 주인은 사람입니다. 되돌리기 어려운 작업, 삭제, 비밀번호·열쇠(키) 관련, 배포와 관련된 일은 반드시 먼저 물어보세요.",
  runbookTitle: (project) => `${project} 만들기`,
  runbookIntro:
    "이게 만드는 순서입니다. 위에서부터 차례대로 하시면 됩니다. " +
    "각 단계마다 복사해서 붙여넣을 지시문이 준비돼 있으니 직접 쓰실 필요 없습니다.",
  teamHeading: "내 AI 팀",
  planHeading: "진행 순서",
  phaseLabel: (n) => `${n}단계`,
  independentNote:
    "이 작업들은 서로 상관이 없습니다. 그래도 하나씩 하세요 — 같은 폴더에서 둘을 동시에 돌리면 서로의 작업을 덮어씁니다.",
  sequentialNote: "이걸 끝내고 다음 단계로 가세요.",
  stepHeading: (n, title) => `${n}번 — ${title}`,
  howToRun: (tool) => `이 프로젝트 폴더에서 ${tool}를 여세요.`,
  copyPromptFrom: (path) => `${path} 파일 내용을 전부 복사해서 붙여넣으세요.`,
  whenFinished: "AI가 끝났다고 하면 위 목록을 확인하고 다음 단계로 넘어가세요.",
  allDone: "여기까지가 전부입니다. 이제 프로젝트가 돌아갈 겁니다.",
  claudeMdIntro:
    "Claude Code를 위한 프로젝트 안내입니다. 이 저장소에서 일하는 모든 에이전트가 이 파일을 읽습니다.",
  agentsMdIntro: "Codex를 위한 프로젝트 안내입니다. 이 저장소에서 일하는 모든 에이전트가 이 파일을 읽습니다.",
  generatedBy: "vibeRACI가 생성함",
  doNotEditByHand: "이 파일을 직접 고치지 말고 계획을 수정한 뒤 다시 생성하세요 — 덮어써집니다.",
};

const table: Record<Locale, Strings> = { en, ko };

export function strings(locale: Locale): Strings {
  return table[locale];
}

const toolNames: Record<string, string> = {
  "claude-code": "Claude Code",
  codex: "Codex",
};

export function toolName(id: string): string {
  return toolNames[id] ?? id;
}
